#Comment to trigger commit
version: 2
jobs:
  build:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: ls -la /var/run/docker.sock
      - run: |
           TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_LOGIN/circleci-demo-docker3 -t $DOCKER_LOGIN/circleci-demo-docker3:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin 
            docker push $DOCKER_LOGIN/circleci-demo-docker3

      
  build1:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
 #     - run:
 #         name: Compile samplescala dist package
 #         command: cat /dev/null | sbt clean update dist
      - run: |
            echo "Hello World!"
            sleep 20
      - store_artifacts:
          path: target/universal/samplescala.zip
          destination: samplescala
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      
  build2:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build3:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build4:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build5:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20 

  build6:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build7:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build1
      - build2
#      - build3
#      - build4
#      - build5
#      - build6
#      - build7
