version: 2
jobs:
  build:
    working_directory: ~/environment/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    steps:
      - restore_cache:
          key: sbt-cache-2
      - run:
          name: Compile samplescala dist package
          command: cat /dev/null | sbt clean update compile package run 
      - save_cache:
          key: sbt-cache-2
          paths:
            - "/tmp/.ivy2/cache"
            - "/tmp/.sbt"
            - "/tmp/.m2"

workflows:
  version: 2
  build_test:
    jobs:
      - build
