version: 2
jobs:
  build:
    working_directory: ~/samplescala
    docker:
      - image: openjdk:8
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - checkout
#      - restore_cache:
#          key: sbt-cache
      - run:
          name: Compile samplescala dist package
          command: cat /dev/null | sbt clean update dist
      - store_artifacts:
          path: target/universal/samplescala.zip
          destination: samplescala
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"

  deploy:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner
    steps:
      - run:
          command: |
              cp target/universal/samplescala.zip target/universal/$ARTIFACT_BUILD
              aws s3 cp target/universal/$ARTIFACT_BUILD s3://briansrv3-data/builds/samplescala/ --metadata {\"git_sha1\":\"$CIRCLE_SHA1\"}

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - deploy:
         requires:
           - build
