#Comment to trigger commit
version: 2
jobs:
  build1:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache
      - run:
          name: Compile samplescala dist package
          command: cat /dev/null | sbt clean update dist
      - run: |
            echo "Hello World!"
            sleep 20
      - store_artifacts:
          path: target/universal/samplescala.zip
          destination: samplescala
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
      - persist_to_workspace:
          root: .
          paths:
            - .

  build21:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-vm
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: |
           TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKER_LOGIN/circleci-demo-docker3 -t $DOCKER_LOGIN/circleci-demo-docker3:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_LOGIN/circleci-demo-docker3
      
  build2:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build3:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build4:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build5:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20 

  build6:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build7:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: | 
            echo "Hello World!"
            sleep 20

  build8:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20
  
  build9:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build10:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build11:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build12:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build13:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build14:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build15:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build16:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build17:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build18:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build19:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

  build20:
    working_directory: ~/samplescala
    machine: true
    resource_class: brianoh1979/brian-runner-k8s
    environment:
      - SBT_VERSION: 1.0.4
    steps:
      - checkout
      - run: |
            echo "Hello World!"
            sleep 20

workflows:
  version: 2
  build_and_test:
    jobs:
      - build1
#      - build2
#      - build3
#      - build4
#      - build5
#      - build6
#      - build7
#      - build8
#      - build9
#      - build10
#      - build11
#      - build12
#      - build13
#      - build14
#      - build15
#      - build16
#      - build17
#      - build18
#      - build19
#      - build20
      - build21:
          requires:
            - build1
